### MSSV: 1712828 - Huỳnh Thanh Khải Trân

In [3]:
import numpy as np
from fractions import Fraction


##### Câu 1:
$$ Pr(X0=2) = 1- Pr(X0=1) - Pr(X0=0) = \frac{1}{2} $$
Phân phối của X0 là: $$ \alpha = [\frac{1}{4},\frac{1}{4},\frac{1}{2}] $$

In [46]:

p=np.matrix([
    [1/2, 1/6, 1/3],
    [0, 2/3, 1/3],
    [1/2, 0, 1/2]
])
X0 = np.matrix([[1/4, 1/4, 1/2]])

In [45]:
#cau a -- ma tran 2 buoc chuyen tu trang thai 1 sang trang thai 0 
print('a) P(X9=0|X7=1)=', (p**2)[1,0])

a) P(X9=0|X7=1)= 0.16666666666666666


#### câu b

Dùng định lý Bayes ta có:
$$P(X_0 = 2| X_1 = 1) = \frac{P(X_0 = 2)P(X_1=1 | X_0=2)}{P(X_1=1)}$$

In [11]:
X1 = X0*p
print(X1)

[[0.375      0.20833333 0.41666667]]


In [44]:
print('ket qua P(X0=2|X1=1)=',X0[0,2]*p[2, 1]/X1[0,1])

ket qua P(X0=2|X1=1)= 0.0


#### câu c
Dùng định lý Bayes ta có:
$$P(X_1 = 2| X_3 = 2) = \frac{P(X_1 = 2)P(X_3=2 | X_1=2)}{P(X_3=2)}$$

In [22]:
X3 = X0*(p**3)
print(X3)

[[0.39930556 0.20023148 0.40046296]]


In [41]:
print('ket qua P(X1=2|X3=1)=',X1[0, 2]*(p**2)[2,2]/X3[0, 2])

ket qua P(X1=2|X3=1)= 0.4335260115606936


#### câu d: 

In [24]:
#cau d
X3 = X0*(p**3)
print(X3)

[[0.39930556 0.20023148 0.40046296]]


Khi đó, ta có:
    $$ E(X_3) = \sum_{i \in S} i P(X_3 = i) $$

In [26]:
S = np.matrix([
    [0],
    [1],
    [2]
])
print(S)

[[0]
 [1]
 [2]]


In [27]:
E_X3 = X3 * S
print(E_X3)

[[1.00115741]]


#### Câu 2:

Ta có:
$$ A = \{X_0, X_1, X_2, ...\} $$
$$ A = \{X_0, X_0 * P, X_0 * P^2, ...\} $$
Ta có: 
$$ B = \{Y_0, Y_1, Y_2, ...\} $$
$$ B = \{X_0, X_3, X_6, ...\} $$
$$ B = \{X_0, X_0 * P^3, X_0 * P^6, ...\} $$
$$ B = \{X_0, X_0 * (P^3)^1, X_0 * (P^3)^2, ...\}$$

Vậy $ B = \{Y_0, Y_1, Y_2, ...\} $ với $Y_n = X_3n$ là một xích Markov với $P = P^3$





#### Câu 3:

Thay thế các bi là một xích markov với ma trận chuyển trạng thái:

$\begin{bmatrix}0.7&0.3\\0.3&0.7\end{bmatrix}$

với tập trạng thái là $S=\{0,1\}$ (đỏ:0; đen:1)


In [36]:
import numpy as np
p3=np.matrix([
    [0.7, 0.3],
    [0.3, 0.7]
])
print(p1)

[[0.7 0.3]
 [0.3 0.7]]


Vì ban đầu trong hộp toàn bi đỏ đỏ nên $X0=0$. <br> Do đó xác xuất để lần 5 vẫn bốc dc bi đỏ là:<br>
$Pr(X_4=0|X_0=0)=P_{0 0}^{(4)}$ (do đếm từ 0; 5 lần bốc => 4 lần chuyển trạng thái)

In [39]:
X_0 = 0;
#Xác xuất bốc được bi đỏ ở lần thứ 5:
X_4 = p3**4
print('Xac xuat la: ',X_4[0,0])

Xac xuat la:  0.5127999999999999
